//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionTool.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bundesland
    {
        public Bundesland()
        {
            this.CandidateLists = new HashSet<CandidateList>();
            this.IsElectableParties = new HashSet<IsElectableParty>();
            this.PopulationBundeslands = new HashSet<PopulationBundesland>();
            this.Wahlkreis = new HashSet<Wahlkrei>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CandidateList> CandidateLists { get; set; }
        public virtual ICollection<IsElectableParty> IsElectableParties { get; set; }
        public virtual ICollection<PopulationBundesland> PopulationBundeslands { get; set; }
        public virtual ICollection<Wahlkrei> Wahlkreis { get; set; }
    }
}
