//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionTool.Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectionDBEntities : DbContext
    {
        public ElectionDBEntities()
            : base("name=ElectionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllowedToElect> AllowedToElects { get; set; }
        public virtual DbSet<AllowedToElectAmount> AllowedToElectAmounts { get; set; }
        public virtual DbSet<Bundesland> Bundeslands { get; set; }
        public virtual DbSet<CandidateList> CandidateLists { get; set; }
        public virtual DbSet<Election> Elections { get; set; }
        public virtual DbSet<Erststimme> Erststimmes { get; set; }
        public virtual DbSet<ErststimmeAmount> ErststimmeAmounts { get; set; }
        public virtual DbSet<InvalidTokenRequest> InvalidTokenRequests { get; set; }
        public virtual DbSet<IsElectableCandidate> IsElectableCandidates { get; set; }
        public virtual DbSet<IsElectableParty> IsElectableParties { get; set; }
        public virtual DbSet<ParticipationAmount> ParticipationAmounts { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<PartyAffiliation> PartyAffiliations { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PopulationBundesland> PopulationBundeslands { get; set; }
        public virtual DbSet<UsedToken> UsedTokens { get; set; }
        public virtual DbSet<Wahlkrei> Wahlkreis { get; set; }
        public virtual DbSet<Zweitstimme> Zweitstimmes { get; set; }
        public virtual DbSet<ZweitstimmeAmount> ZweitstimmeAmounts { get; set; }
        public virtual DbSet<BasicWahlkreisOverview> BasicWahlkreisOverviews { get; set; }
        public virtual DbSet<ClosestErststimmeResult> ClosestErststimmeResults { get; set; }
        public virtual DbSet<ClosestZweitstimmeResult> ClosestZweitstimmeResults { get; set; }
        public virtual DbSet<DistributionWithinState> DistributionWithinStates { get; set; }
        public virtual DbSet<ElectionParticipation> ElectionParticipations { get; set; }
        public virtual DbSet<ErststimmeAggregated> ErststimmeAggregateds { get; set; }
        public virtual DbSet<ErststimmeWahlkreisOverview> ErststimmeWahlkreisOverviews { get; set; }
        public virtual DbSet<minSeatsPerParty_Bundeslevel> minSeatsPerParty_Bundeslevel { get; set; }
        public virtual DbSet<ParliamentMember> ParliamentMembers { get; set; }
        public virtual DbSet<Parties5> Parties5 { get; set; }
        public virtual DbSet<SeatsGainedByErststimme> SeatsGainedByErststimmes { get; set; }
        public virtual DbSet<seatsGainedByZweitstimme> seatsGainedByZweitstimmes { get; set; }
        public virtual DbSet<SeatsPerState> SeatsPerStates { get; set; }
        public virtual DbSet<Sitzverteilung> Sitzverteilungs { get; set; }
        public virtual DbSet<Ueberhangmandate> Ueberhangmandates { get; set; }
        public virtual DbSet<Wahlkreissieger> Wahlkreissiegers { get; set; }
        public virtual DbSet<WinnerErststimme> WinnerErststimmes { get; set; }
        public virtual DbSet<WinnerFirstAndSecondVote> WinnerFirstAndSecondVotes { get; set; }
        public virtual DbSet<WinnerZweitstimme> WinnerZweitstimmes { get; set; }
        public virtual DbSet<ZweitstimmeAggregated> ZweitstimmeAggregateds { get; set; }
        public virtual DbSet<ZweitstimmenState> ZweitstimmenStates { get; set; }
        public virtual DbSet<ZweitstimmeWahlkreisOverview> ZweitstimmeWahlkreisOverviews { get; set; }
    }
}
