//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionTool.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErststimmeWahlkreisOverview
    {
        public int election_id { get; set; }
        public int wahlkreis_id { get; set; }
        public string Wahlkreis_Name { get; set; }
        public Nullable<int> person_id { get; set; }
        public string title { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> Party_Id { get; set; }
        public string Party_Name { get; set; }
        public int Votes { get; set; }
        public Nullable<int> overall { get; set; }
        public Nullable<decimal> PercentVotes { get; set; }
        public Nullable<decimal> Previous { get; set; }
    }
}
