//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionTool.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.IsElectableParties = new HashSet<IsElectableParty>();
            this.PartyAffiliations = new HashSet<PartyAffiliation>();
            this.Zweitstimmes = new HashSet<Zweitstimme>();
            this.ZweitstimmeAmounts = new HashSet<ZweitstimmeAmount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<IsElectableParty> IsElectableParties { get; set; }
        public virtual ICollection<PartyAffiliation> PartyAffiliations { get; set; }
        public virtual ICollection<Zweitstimme> Zweitstimmes { get; set; }
        public virtual ICollection<ZweitstimmeAmount> ZweitstimmeAmounts { get; set; }
    }
}
