//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionTool.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.AllowedToElects = new HashSet<AllowedToElect>();
            this.CandidateLists = new HashSet<CandidateList>();
            this.Erststimmes = new HashSet<Erststimme>();
            this.IsElectableCandidates = new HashSet<IsElectableCandidate>();
            this.PartyAffiliations = new HashSet<PartyAffiliation>();
            this.Elections = new HashSet<Election>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    
        public virtual ICollection<AllowedToElect> AllowedToElects { get; set; }
        public virtual ICollection<CandidateList> CandidateLists { get; set; }
        public virtual ICollection<Erststimme> Erststimmes { get; set; }
        public virtual ICollection<IsElectableCandidate> IsElectableCandidates { get; set; }
        public virtual ICollection<PartyAffiliation> PartyAffiliations { get; set; }
        public virtual ICollection<Election> Elections { get; set; }
    }
}
