//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionTool.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitzverteilung
    {
        public int Election_Id { get; set; }
        public Nullable<int> OverallSeats { get; set; }
        public Nullable<int> Party_Id { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> SeatsParty { get; set; }
        public Nullable<decimal> PercentParty { get; set; }
    }
}
